version: "3.9"

services:
  app:
    build: .
    ports:
      - "9090:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vprofile
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - vprofile-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: vprofile
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - vprofile-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vprofile-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  vprofile-net:

volumes:
  mysql-data:
